const t_arrays_all = [
  [// Greetings
    ['Hello I am a man.', 'Hallo ich bin', 'Mann', ['ein', 'einen', 'einem', 'eine']],
    ['Where do we live?.', 'Wo', 'wir?', ['leben', 'lebe', 'lebt', 'liebst']],
    ['How old is your brother?.', 'Wie', 'ist dein Bruder?', ['alt', 'jung', 'herr', 'seit']],
    ['What do you do for a living?.', 'Was', 'du als Beruf?', ['machst', 'tuest', 'tut', 'arbeitest']],
    ['What would you like to eat?.', 'Was', 'sie gern?', ['hatten', 'habt', 'hast', 'haben']],
    ['What do you do in your free time?.', 'Was', 'du in deiner Freizeit?', ['machst', 'spielst', 'weinst', 'gehts']],
    ['Do you have a big family?.', 'Hast', 'eine große Familie?', ['du', 'wir', 'Ich', 'sie']],
    ['Do you live with your family?.', 'Lebst du mit', 'Familie?', ['deiner', 'die', 'das', 'denen']],
    ['What is your education level?.', 'Was ist dein', '?', ['Ausbildungsniveau', 'Sprachniveau', 'Hörniveau', 'Problem']],
    ['Do you prefer cats or dogs?.', '', 'du Katzen oder Hunde?', ['Magst', 'Liebst', 'Hasst', 'Denkst']],
    ['Where do you see yourself in 5 minutes?.', 'Wo siehst du', 'in 5 Minutes?', ['dich', 'sich', 'mich', 'dein']],
    ['How was your day?.', 'Wie', 'dein Tag?', ['war', 'warst', 'ist', 'wurdest']],
    ['I can not start my day without coffee.', 'Ich kann meinen Tag nicht', 'Kaffee beginnen.', ['ohne', 'mit', 'gerne', 'würde']],
    ['I like to dream about my future.', 'Ich träume gerne von meiner', '.', ['Zukunft', 'Leben', 'Traum', 'Auto']],
    ['Painting and listening music are my hobbies.', '', 'und Musik hören sind meine Hobbys.', ['malen', 'streichen', 'gewinnen', 'hören']],
    ['Red is of course my favorite color.', 'Rot ist', 'meine Lieblingsfarbe.', ['natürlich', 'nie', 'immer', 'genau']],
    ['My sister is my favorite family member.', 'Meine Schwester ist mein', '.', ['Lieblingsfamilienmitglied', 'Naturwissenschaft', 'Schmetterling', 'Lieblingskugelschreiber']],
    ['I love coding in my free time.', 'Ich liebe es in meiner Freizeit zu', '.', ['Programmieren', 'Zeichnen', 'Malen', 'Computieren']],
    ['I like spending time with my friends.', 'Ich', 'gerne Zeit mit meinen Freunden.', ['verbringe', 'spende', 'lebe', 'treffe']],
  ],
  [ // Clothing
    ['I love wearing my red trousers.', 'Ich liebe es, meine rote Hose zu', '.', ['tragen', 'wearen', 'sinken', 'trennen']],
    ['You wrapped this red scarf around my neck.', 'Du hast diesen roten Schal um meinen Hals', '. ', ['gewickelt', 'getroffen', 'gelegen', 'gestellt']],
    ['Mikasa loves wearing that red scarf.', 'Mikasa liebt es, diesen roten', 'zu tragen. ', ['Schal', 'Hemd', 'Shorts', 'BH']],
    ['Annie always wears the same white sweater.', 'Annie trägt immer den gleichen weißen', '. ', ['Pullover', 'Schuhe', 'Hose', 'BH']],
    ['Where did you buy those boots?', 'Wo hast du diese', 'gekauft? ', ['Stiefel', 'Schuhe', 'Handschuhe', 'Jeans']],
    ["Monica's boots are very expensive.", 'Monicas Stiefel sind sehr', '. ', ['teuer', 'billig', 'günstig', 'liebe']],
    ['Beatrix wears yellow shoes.', 'Beatrix trägt gelbe', '. ', ['Schuhe', 'Stiefel', 'Hemd', 'BH']],
    ['I wear the same boxers for a week.', 'Ich trage eine Woche lang die', 'Boxer. ', ['gleichen', 'selben', 'schwarzen', 'roten']],
    ['Rachel protected her laundry machine.', 'Rachel schützte ihre', '. ', ['Waschmaschine', 'Kugelschreiber', 'Geschirrspüler', 'Krankenwagen']],
    ['Chandler loves wearing sweaters.', 'Chandler liebt es, Pullover zu', '. ', ['tragen', 'trennen', 'gleichen', 'reparieren']],
    ['My best friend got me those earrings.', 'Mein bester Freund hat mir diese', 'besorgt. ', ['Ohrringe', 'Armband', 'Stiefel', 'Halskette']],
    ['I am going to buy new shoes today.', 'Ich werde heute', 'Schuhe kaufen. ', ['neue', 'gelbe', 'nette', 'rote']],
    ['The necklace I got you was golden.', 'Die', ',die ich dir besorgt habe, war golden.. ', ['Kette', 'Armband', 'Ohrringe', 'Schuhe']],
    ['I like men who wear gold bracelets.', 'Ich mag Männer, die goldene', 'tragen. ', ['Armbander', 'Halskette', 'Ohrringe', 'Schal']],
    ['How much did you pay for that shirt?', 'Wie viel hast du für', 'Shirt bezahlt? ', ['dieses', 'diesem', 'diesen', 'diese']],
    ['There is a discount on the shoes.', 'Es gibt einen', 'auf die Schuhe.', ['Rabatt', 'Verkauf', 'Costen', 'Kaufzeit']],
    ['I love those colors on your pullover.', 'Ich liebe diese Farben auf', 'Pullover.', ['deinem', 'deinen', 'deiner', 'deines']]
  ],
  [ // Travel
    ['How can I go from here to Bratislava?', 'Wie kann ich von hier nach Bratislava', '?', ['fahren', 'teleportieren', 'fliegen', 'erreichen']],
    ['How much will the plane tickets cost?', 'Wie viel kosten die', '?', ['Flugtickets', 'Bustickets', 'Aerotickets', 'Flughafen']],
    ['I will take a ferry to Kadıköy.', 'Ich werde eine', 'nach Kadıköy nehmen.', ['Fahre', 'Schiff', 'Schildkröte', 'Bus']],
    ['How far is it if we take the norhtern route?', 'Wie', 'ist es, wenn wir die Nordroute nehmen?', ['klar', 'gleich', 'fertig', 'einfach']],
    ["The flight won't be cancelled.", 'Der Flug wird nicht', '.', ['stoniert', 'gelöscht', 'gemischt', 'gestolpert']],
    ['The way is shut said the ghost to Aragorn.', 'Der', 'ist verschlossen, sagte der Geist zu Aragorn.', ['Weg', 'Tür', 'Tor', 'Mauer']],
    ['Gandalf will ride Shadowfangs to Minas Tirith.', 'Gandalf wird Shadowfangs nach Minas Tirith', '.', ['reiten', 'gehen', 'stolpern', 'springen']],
    ['In Germany there are no speed limits.', 'In Deutschland gibt es keine', '.', ['Geschwindigkeitsbegrenzungen', 'Schmetterlinglimit', 'Kartoffelsalat', 'Wassermelonenbegrenzungen']],
    ['Bilbo goes on an unexpected journey.', 'Bilbo geht auf eine unerwartete', '.', ['reise', 'betrieb', 'trip', 'tour']],
    ['Elves are dangerous in long distance.', 'Elfen sind in großer', 'gefährlich.', ['Entfernung', 'Weit', 'Flugzeug', 'Bahnhof']],
    ['It is 70 kilometers between Wall Maria and Wall Rose.', 'Es ist 70 Kilometer', 'Wall Maria und Wall Rose.', ['zwischen', 'auto', 'neben', 'gleich']],
    ['Have you ever been on a yatch?', 'Waren Sie schon einmal auf einer', '?', ['Yatch', 'Schiff', 'Aeroplane', 'Kreuzfahrt']],
    ['There are about 20 minutes delay on my flight.', 'Mein Flug hat ungefähr 20 Minuten', '.', ['Verspatung', 'Stornierung', 'Annahme', 'Grenze']],
    ["I do not have a driver's license.", 'Ich habe keinen', '.', ['Führerschein', 'Führerskarte', 'Führersplate', 'Führerausweis']],
    ['We have to pass that bridge.', 'Wir müssen diese', 'passieren.', ['Brücke', 'Perücke', 'Mücke', 'Jacke']],
    ['Take me to the airport in 30 minutes.', '', ' mich in 30 Minuten zum Flughafen.', ['Bring', 'Liefer', 'Teleportieren', 'Gedehen']]
  ],
  [ // Animals 

    ['I love playing with our dog.', 'Ich liebe es mit', 'Hund zu spielen.', ['unserem', 'unseren', 'unser', 'unsere']],
    ['Why dogs and cats hate each other.', 'Warum Hunde und', 'sich hassen.', ['Katzen', 'Nilpferden', 'Giraffen', 'Nudeln']],
    ['I need some cat litter.', 'Ich brauche', '.', ['Katzenstreu', 'Katzenfuttern', 'Hundenstreu', 'Vögelnfuttern']],
    ['We used to have a bird.', 'Wir hatten früher einen', '.', ['Vogel', 'Pferd', 'Esel', 'Ziege']],
    ['Shrek loves going with donkey.', 'Shrek liebt es, mit', 'zu gehen.', ['Eseln', 'Ziegen', 'Drachen', 'Pferden']],
    ['Fiona made the bird sing.', 'Fiona', 'den Vogel singen.', ['ließ', 'hast', 'schrumpfen', 'liest']],
    ['Levi hates that monkey.', 'Levi hasst diesen', '.', ['Affe', 'Papagei', 'Vogel', 'Bock']],
    ['We must stop that okapi.', 'Wir müssen das Okapi', '.', ['aufhalten', 'töten', 'fallen', 'lassen']],
    ['Aang learned from that turtle.', 'Aang lernte von dieser', '.', ['Schildkröte', 'Meerkat', 'Löwe', 'Elepahnt']],
    ['Dany had three full grown dragons.', 'Dany hatte drei ausgewachsene', '.', ['Drachen', 'Einhörnen', 'Lepricons', 'Zwergen']],
    ['Gandalf has a horse named Shadow Fangs.', 'Gandalf hat ein', 'namens Shadow Fangs.', ['Pferd', 'Horse', 'Affe', 'Tiger']],
    ['Sun misses only her dog.', 'Sun vermisst nur', ' Hund.', ['ihren', 'ihrem', 'ihre', 'ihrer']],
    ['Zuko has a lovely ferret.', 'Zuko hat ein schönes', '.', ['Frettchen', 'Frettche', 'Frettchy', 'Ferretchen']],
    ['Phoebe has seven rats.', 'Phoebe hat sieben', '.', ['Ratten', 'Mousen', 'Frapeen', 'Rats']],
    ['Dog is barking very loud tonight.', 'Hund', ' heute Abend sehr laut.', ['bellt', 'hüllt', 'berüllt', 'knappt']],
    ['The ox has very strong legs.', 'Der', 'hat sehr starke Beine.', ['Ochse', 'Oxen', 'Lopfen', 'Oksen']],
    ['The bees are making honey.', 'Die', 'machen Honig.', ['Bienen', 'Beeren', 'Mienen', 'Meepen']],
    ['The cow gives 4 liters of milk everyday.', 'Die Kuh gibt', ' 4 Liter Milch.', ['täglich', 'tagsüber', 'tagenden', 'wochig']],
    ['Camels store water and fat in their backs.', 'Kamele', 'Wasser und Fett im Rücken.', ['speichern', 'liefern', 'berühren', 'stonieren']],
    ['Appa is a flying bison.', 'Appa ist ein', 'Bison.', ['fliegender', 'laufender', 'singender', 'kartofender']],
    ['The snakes can not walk.', 'Die', 'können nicht laufen.', ['Schlangen', 'Scherren', 'Laufenden', 'Knallen']],
    ['An ostrich can catch up with a cheetah.', 'Ein Strauß kann einen', ' einholen.', ['Geparden', 'Geopardeen', 'Cheetas', 'Chetaen']]
  ],
  [ // Food
    ['We need more flour.', 'Wir brauchen mehr', '.', ['Mehl', 'Honig', 'Salz', 'Pfeffer']],
    ["Phoebe's cookies are great.", 'Phoebes', 'sind großartig.', ['Kekse', 'Nudel', 'Ramen', 'Torten']],
    ['This turkey is ready.', 'Dieser', 'ist fertig.', ['Truthanh', 'Hahnchen', 'Speck', 'Torte']],
    ['Put  a little bit salt in the cake mix.', 'Geben Sie etwas', 'in die Kuchenmischung.', ['Salz', 'Pfeffer', 'Honig', 'Zitronen']],
    ["Max's homemade cupcaked are amazing.", "Max", "Cupcakes sind unglaublich.", ['Hausgemachte', 'Handgemachte', 'Ladengemachte', 'Frischgebackt']],
    ['I love putting tomato paste in the pasta.', 'Ich liebe es,', 'in die Pasta zu geben.', ['Tomatenmark', 'Tomatenpaste', 'Tomategrübs', 'Tomatengrabeln']],
    ['Phoebe does not eat meat.', 'Phoebe isst kein', '.', ['Fleisch', 'Hahnchen', 'Gurken', 'Auberginen']],
    ['My favorite dish is İskender.', 'Mein', 'ist İskender.', ['Lieblingsgericht', 'Lieblingskuchen', 'Lieblisngsbild', 'Lieblingsnudeln']],
    ['We will eat two wraps each.', 'Wir werden', 'zwei Wraps essen.', ['jeweils', 'jegendem', 'jeweilig', 'jedentag']],
    ['Make mine extra hot please.', 'Mach mir bitte extra', '.', ['heiß', 'süß', 'klar', 'hitzig']],
    ['She wants only chicken and salad.', 'Sie will nur', 'und Salat.', ['Hühnchen', 'Schicken', 'Speck', 'Spetzle']],
    ['There are people who prefer it gluten-free.', 'Es gibt Leute, die es', 'bevorzugen.', ['glutenfrei', 'glutenlos', 'ohn-gluten', 'glutenvoll']],
    ['Add some garlic with the pickles to the jar.', 'Fügen Sie etwas', 'mit den Gurken zum Glas hinzu.', ['Knoblauch', 'Olche', 'Hühne', 'Zwiebeln']],
    ['Joey does not share food.', 'Joey', 'sein Essen nicht.', ['teilt', 'bevorzugt', 'mittelt', 'tript']],
    ['Phoebe does not eat veal.', 'Phoebe isst kein', '.', ['Kalbfleisch', 'Rindfleisch', 'Schweinfleisch', 'Rotfleisch']],
    ['Rosemary makes almost everything better.', '', 'macht fast alles besser.', ['Rosmarin', 'Rosemari', 'Genseblümchen', 'Rosemaree']],
    ['Stop adding curry to the cake.', 'Hör auf, dem', 'Curry hinzuzufügen.', ['Kuchen', 'Backen', 'Gurken', 'Zocken']],
    ['Fries are the best food in the world.', '', 'sind das beste Essen der Welt.', ['Pommes', 'Gefrittes', 'Gebacktes', 'Gewürzelts']],
    ['Donuts are just fancy bagels.', 'Donuts sind nur', 'Bagels.', ['schicke', 'klasse', 'protzig', 'hassliche']]
  ],
  [ // Education 
    ['What is your major?', 'Was ist dein', '?', ['Hauptfach', 'Liebfach', 'Spezision', 'Branch']],
    ['When does the class start?', 'Wann beginnt der', '?', ['Unterricht', 'Klasse', 'Leccion', 'Lektion']],
    ['I failed this class as well.', 'Ich habe diese Klasse auch nicht', '.', ['bestanden', 'gegraben', 'gelöscht', 'gewonnen']],
    ['I am taking this class for the third time.', 'Ich nehme zum dritten Mal an', 'Kurs teil.', ['diesem', 'diesen', 'dieser', 'diese']],
    ['I always hated that professor.', 'Ich habe diesen', 'immer gehasst.', ['Professor', 'Unterrichter', 'Lektioner', 'Lehrer']],
    ['I can not see the blackboard.', 'Ich kann', 'nicht sehen.', ['die Tafel', 'der Tisch', 'die Kabel', 'die Puppe']],
    ['Did you apply for a scholarship?', 'Haben Sie sich für ein', 'beworben?', ['Stipendium', 'Schulenkarte', 'Studentbörse', 'Studentium']],
    ['Can I borrow your homework tonight?', 'Kann ich mir heute Abend deine', 'ausleihen?', ['Hausaufgaben', 'Hauswork', 'HW', 'Hauswerk']],
    ['He is a total freeloader.', 'Er ist ein totaler', '.', ['Schmarotzer', 'Haltenroter', 'Kugelschreiber', 'Meerkat']],
    ['That is called plagiarism.', 'Das nennt man', '.', ['Plagiat', 'Plagieren', 'Kopieren', 'Genseblümchen']],
    ['This final is worth 90% of the total mark.', 'Dieses Finale ist 90% der', 'wert.', ['Gesamtnote', 'Hauptmark', 'Tomatenmark', 'Ganzemark']],
    ['I love task based lessons.', 'Ich liebe', 'Unterricht.', ['aufgabenbasierten', 'hauswerkenbasiert', 'schompfenbasiert', 'wassermelonen']],
    ['Equally share the workload.', 'Teilen Sie die Arbeitslast', '.', ['gleichermaßen', 'ganzenmaßen', 'genauermaßen', 'totalmaßen']],
    ['Where is your campus?', 'Wo ist dein', '?', ['Campus', 'Unistadt', 'Hochschule', 'Unibereich']],
    ['Can you record the lecture for me?', 'Können Sie den Vortrag für mich', '?', ['aufnehmen', 'aufberühren', 'aufzetzen', 'aufröhren']],
    ['I love listening to his lectures.', 'Ich liebe es, seinen Vorträgen', '.', ['zuzuhören', 'zuklaren', 'zusehen', 'zusehen']],
    ['She is a hard-working student.', 'Sie ist eine', 'Studentin', ['fleißige', 'faulige', 'haarige', 'weissige']],
    ['Who is the smartest in the class?', 'Wer ist der', 'in der Klasse?', ['klügste', 'schönste', 'glaubste', 'klarste']]
  ],
  [ // Relatinship
    ['Will you go out with me?', 'Wirst du mit mir', '?', ['ausgehen', 'daten', 'küssen', 'lieben']],
    ['Where are we in this relationship?', 'Wo sind wir in dieser', '?', ['Beziehung', 'Liebhaben', 'Küssenpaare', 'Liebenpaarheit']],
    ['I like sleeping near you.', 'Ich schlafe gern in', 'Nähe.', ['deiner', 'deinem', 'deine', 'dein']],
    ['He got a new perfume for him.', 'Er hat ein neues Parfüm für', ' bekommen.', ['ihn', 'ihm', 'ihr', 'sie']],
    ['I am really not interested in you.', 'Ich interessiere mich', 'nicht für dich.', ['wirklich', 'gar', 'genauer', 'gerne']],
    ['He likes spoiling him.', 'Er', 'ihn gern.', ['verwöhnt', 'liebt', 'spielt', 'lügt']],
    ['There are no excuses for cheating.', 'Es gibt keine Ausreden für', '.', ['Fremdgehen', 'Lügenlieben', 'Lieblügen', 'Fremdküssen']],
    ['They were on a break.', 'Sie machten eine', '.', ['Pause', 'Ausrede', 'Liebespeichen', 'Kugelscreiber']],
    ['He does not want to be married.', 'Er will nicht', 'sein.', ['verheiratet', 'geheiratet', 'geliebt', 'glücklich']],
    ['I rarely care for people.', 'Ich', 'mich selten um Menschen.', ['kümmere', 'liebe', 'gerne', 'süppere']],
    ['Those three are in a relationship.', 'Diese drei sind in einer', '.', ['Beziehung', 'Liebendritte', 'Suppe', 'Gericht']],
    ['I am not interested in weirdos.', 'Ich bin nicht an', 'interessiert.', ['Verrückten', 'Küsseren', 'Genseblümchen', 'Dreizacken']],
    ["I think he's very cute.", 'Ich', 'ihn sehr süß.', ['finde', 'denke', 'danke', 'speiche']],
    ['We like doing stuff together.', 'Wir machen gerne Sachen', '.', ['zusammen', 'zugleich', 'zustimmen', 'zuckervoll']],
    ['Marriage is a big decision.', 'Die Ehe ist eine große', '.', ['Entscheidung', 'Getrennung', 'Entsprechen', 'Verantwortung']],
    ['I always wanted 3 kids.', 'Ich wollte immer 3', '.', ['Kinder', 'Kindern', 'Kinds', 'Kindeln']],
    ['Can I take you to a wedding as my guest?', 'Kann ich Sie als meinen Gast zu einer Hochzeit', '?', ['mitnehmen', 'mitgehen', 'mitspringen', 'mitbringen']],
    ['Trust and confidence is very important in a relationship.', '', 'und Zuversicht sind in einer Beziehung sehr wichtig.', ['Vertrauen', 'Liebe', 'Veranwortung', 'Vergleichung']],
    ['He deserves a second chance.', 'Er hat eine zweite Chance', '.', ['verdient', 'vercheckt', 'verhielt', 'verstoppen']]
  ]
]


export { t_arrays_all }