const f_arrays_all = [
  [ // Greetings
    ['What is your name?', 'Was ist dein Name?'],
    ['How old are you?', 'Wie alt bist du?'],
    ['Where are you from?', 'Woher kommst du?'],
    ['Where do you live?', 'Wo wohnst du?'],
    ['Where do you work?', 'Wo arbeitest du?'],
    ['I have a brother.', 'Ich habe einen Bruder.'],
    ['Do you have a sister?', 'Hast du eine Schwester?'],
    ["What is your mother's name?", 'Wie heißt deine Mutter?'],
    ["How old is your dad?", 'Wie alt ist dein Vater?'],
    ["What is your brother's name?", 'Wie heißt dein Bruder?'],
    ['Do you have an aunt or an uncle?', 'Hast du eine Tante oder einen Onkel?'],
    ['What music do you listen to?', 'Welche Musik hörst du?'],
    ['Where is your home?', 'Wo ist dein Zuhause?'],
    ['How much money do you make?', 'Wie viel Geld verdienst du?'],
    ['My favorite color is red.', 'Meine Lieblingsfarbe ist rot.'],
    ['I love watching Attack on Titan.', 'Ich liebe es, Attack on Titan zu sehen.'],
    ['I am an easy-going person.', 'Ich bin eine Lockere Person.'],
    ['I am a trustworthy person.', 'Ich bin eine vertrauenswürdige Person'],
    ['I do not lie.', 'Ich lüge nicht.']
  ],
  [ // Clothing
    ['This is my favorite skirt.', 'Das ist mein Lieblingsrock.'],
    ['Here is my blue sweater.', 'Hier ist mein blauer Pullover.'],
    ['You wrapped that red scarf around me.', 'Du hast diesen roten Schal um mich gewickelt.'],
    ['Annie always wears the same white sweatshirt.', 'Annie trägt immer das gleiche weiße Sweatshirt.'],
    ['I borrowed your big ring, I hope it is okay with you.', 'Ich habe mir deinen großen Ring geliehen, ich hoffe, es ist okay für dich.'],
    ["Don't wash the colored ones with your whites.", 'Waschen Sie die farbigen nicht mit Ihren Weißen.'],
    ['Now all your socks are sort of pink.', 'Jetzt sind alle deine Socken irgendwie rosa.'],
    ['What is the color of your pullover?', 'Was ist die Farbe Ihres Pullovers?'],
    ['Mom threw away my favorite sweater.', 'Mama warf meinen Lieblingspullover weg.'],
    ['I will buy me some new shoes.', 'Ich werde mir neue Schuhe kaufen.'],
    ['Do you have anything thick to wear?', 'Hast du etwas Dickes zum Anziehen?'],
    ['Average male has 4 pants and 10 shirts.', 'Durchschnittlicher Mann hat 4 Hosen und 10 Hemden.'],
    ['Bring your coat, it is cold.', 'Bring deinen Mantel mit, es ist kalt.'],
    ['I bought you a red hat.', 'Ich habe dir einen roten Hut gekauft.'],
    ['A pashmina is not a rug.', 'Eine Pashmina ist kein Teppich.'],
    ['I wear shirts with sweatpants.', 'Ich trage Hemden mit Jogginghose.']
  ],
  [ // Travel
    ['Do you have the tickets?', 'Hast du die Tickets?'],
    ['We will have a vacation in Mexico.', 'Wir werden einen Urlaub in Mexiko haben.'],
    ['Love, how far is Frankfurt from Berlin.', 'Schatz, wie weit ist Frankfurt nach Berlin.'],
    ['I will take a train from Bucharest to Bratislava.', 'Ich werde einen Zug von Bukarest nach Bratislava nehmen.'],
    ['Have you ever been on a plane?', 'Warst du jemals in einem Flugzeug?'],
    ['Can we take a ferry instead?', 'Können wir stattdessen eine Fähre nehmen?'],
    ['Where is the closest bus stop from here?', 'Wo ist die nächste Bushaltestelle von hier?'],
    ['There are no buses after 10 am.', 'Nach 10 Uhr gibt es keine Busse mehr'],
    ['We got the last seats on the plane.', 'Wir haben die letzten Plätze im Flugzeug.'],
    ['We are one hour late for the plane.', 'Wir sind eine Stunde zu spät für das Flugzeug.'],
    ['Now we will have to buy bus tickets.', 'Jetzt müssen wir Bustickets kaufen.'],
    ['10 hours bus ride from here to Paris.', '10 Stunden Busfahrt von hier nach Paris.'],
    ['We need to arrive the bus station in 10 minutes.', 'Wir müssen den Busbahnhof in 10 Minuten erreichen.'],
    ['I will arrive in Rio airport in 4 days.', 'Ich werde in 4 Tagen am Flughafen von Rio ankommen.'],
    ['The flight got cancelled.', 'Der Flug wurde abgesagt.'],
    ['I will just take  a taxi instead.', 'Ich nehme stattdessen einfach ein Taxi.'],
    ['I like riding a bike instead of driving a car.', 'Ich fahre gerne Fahrrad, anstatt Auto zu fahren.'],
    ['In german autobahns there are no speed limits.', 'In deutschen Autobahnen gibt es keine Geschwindigkeitsbegrenzungen.']
  ],
  [ // Animals
    ['I like cats more than dogs.', 'Ich mag Katzen mehr als Hunde.'],
    ['I have three cats.', 'Ich habe drei Katzen.'],
    ['The cat is between the doors.', 'Die Katze steht zwischen die Tür.'],
    ['My cat is faster than your dog.', 'Meine Katze ist schneller als dein Hund.'],
    ['The hippopotam is very cute.', 'Der Nilpferd ist sehr niedlich.'],
    ['The monkeys are dangerous.', 'Die Affen sind gefaehrlich.'],
    ['The giraffe has a tall neck.', 'Die Giraffe hat einen langen Hals.'],
    ['The dog is very angry.', 'Der Hund ist sehr wütend..'],
    ["I don't trust cats.", 'Ich traue Katzen nicht.'],
    ['What noise do the foxes make?', 'Welches Geräusch machen die Füchse?'],
    ['Zuko has a ferret as a pet.', 'Zuko hat ein Frettchen als Haustier.'],
    ['My sister accidentally injured a bird.', 'Meine Schwester hat versehentlich einen Vogel verletzt.'],
    ['We used to have a dog but it ran away.', 'Früher hatten wir einen Hund, aber er lief weg.'],
    ['My patronus is a sloth.', 'Mein Patronus ist ein Faultier.'],
    ['Meerkats are very cute.', 'Erdmännchen sind sehr süß.'],
    ['We are feeding the monkeys with nuts.', 'Wir füttern die Affen mit Nüssen.'],
    ['A chicken pooped on my head when I was  a child.', 'Ein Huhn hat mir als Kind auf den Kopf gekackt.'],
    ['That hipopotam is looking at me a bit scary.', 'Das Hipopotam sieht mich ein bisschen gruselig an.']
  ],
  [ // Food
    ['What would you like to order?', 'Was hatten sie gern?'],
    ['We need milk, sugar and butter.', 'Wir brauchen Milch, Zucker und Butter.'],
    ['Fruits or vegetables?', ' Obst oder Gemüse?'],
    ['We ate the whole banana alone.', 'Wir haben die ganze Banane allein.'],
    ['There is not enough salt and pepper left.', 'Gibt es nicht genug Salz und Pfeffer.'],
    ['I like french fries a lot.', 'Ich mag Pommes so sehr.'],
    ['She likes strawberries and grapes.', 'Sie mag Erdbeere und Trauben.'],
    ['Add more water to the soup to dilute salt.', 'Fügen Sie der Suppe mehr Wasser hinzu, um das Salz zu verdünnen.'],
    ['She puts the tomatoes whole to the sandwich.', 'Sie legt die Tomaten ganz ins Sandwich.'],
    ['There should not be pineapple on pizza.', 'Es sollte keine Ananas auf Pizza sein'],
    ['I really like the German cuisine.', 'Ich mag die deutsche Küche sehr.'],
    ['Some people do not consume dairy products.', 'Einige Leute konsumieren keine Milchprodukte.'],
    ['I do not eat vegetables.', 'Ich esse kein Gemüse.'],
    ['You should have more fruits in your diet.', 'Sie sollten mehr Früchte in Ihrer Ernährung haben.'],
    ['Red beets are good for you.', 'Rote Beete sind gut für dich.'],
    ['I have never eaten any deer meat before.', 'Ich habe noch nie Hirschfleisch gegessen.'],
    ['I can eat anything with enough sauce and garlic.', 'Ich kann alles mit genug Sauce und Knoblauch essen.'],
  ],
  [ // Education
    ['I am accepted from that university.', 'Ich werde von dieser Universität angenommen'],
    ['I love my major.', 'Ich liebe mein Hauptfach.'],
    ['I am interested in this lesson.', 'Ich interessiere mich für diese Lektion.'],
    ['I would like to go to that seminar.', 'Ich würde gerne zu diesem Seminar gehen.'],
    ['Share the work equally.', 'Teilen Sie die Arbeit gleichermaßen.'],
    ["You can't borrow my homework.", 'Du kannst meine Hausaufgaben nicht ausleihen.'],
    ['Plagiarism is a crime.', 'Plagiat ist ein Verbrechen.'],
    ['Cheating is not recommended.', 'Betrug wird nicht empfohlen.'],
    ['I have an assignment due tomorrow.', 'Ich habe morgen einen Auftrag.'],
    ["Where is the men's room?", 'Wo ist das Männerzimmer?'],
    ['She is not a bad professor.', 'Sie ist keine schlechte Professorin.'],
    ['He is a lazy student.', 'Er ist ein fauler Schüler.'],
    ['Good luck on the homework.', 'Viel Glück bei den Hausaufgaben.'],
    ['Oh my god, that is my literature teacher!', 'Oh mein Gott, das ist mein Literaturlehrer!'],
    ['Sir, can I please take your course too?', 'Sir, kann ich bitte auch Ihren Kurs belegen?']
  ],
  [ // Relationship
    ['Please make me your husband Jeanette!', 'Bitte mach mich zu deinem Ehemann Jeanette!'],
    ['This is a new dating app.', 'Dies ist eine neue Dating-App'],
    ['I have three dates this week.', 'Ich habe diese Woche drei Termine.'],
    ['I love you.', 'Ich liebe dich.'],
    ['Holding hands is cute.', 'Händchenhalten ist süß.'],
    ['We will have dinner together.', 'Wir werden zusammen zu Abend essen.'],
    ['I love your voice.', 'Ich liebe deine Stimme.'],
    ['Ask her out.', 'Frag sie aus.'],
    ['He is so handsome', 'Er ist so gut aussehend.'],
    ['I love his dimples.', 'Ich liebe seine Grübchen.'],
    ['God I hate him.', 'Gott, ich hasse ihn.'],
    ['We are going out with him.', 'Wir gehen mit ihm aus.'],
    ['We are in a happy relationship.', 'Wir sind in einer glücklichen Beziehung.'],
    ['In relationship there are compromises.', 'In der Beziehung gibt es Kompromisse.'],
    ['Once a cheater, always a cheater.', 'Einmal ein Betrüger, immer ein Betrüger.'],
    ['Maybe we should move in together.', 'Vielleicht sollten wir zusammenziehen.']
  ]
]

export { f_arrays_all }


